db:
  uri: "mongodb://localhost:27017"
  name: "ir_crawler"

logic:
  delay: 0.8
  user_agent: "IR-Student-Crawler/2.0 (edu)"
  recrawl_after_seconds: 4000000

limits:
  wikipedia: 26000
  securitylab: 900
  securitynews: 27000

seeds:
  - source: "wikipedia"
    url: "https://ru.wikipedia.org/wiki/Категория:Информационная_безопасность"

